# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-31 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='user',
            new_name='userdata',
        ),
    ]
