# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-31 16:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180331_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_name',
            field=models.CharField(default=datetime.datetime(2018, 3, 31, 16, 37, 30, 365357, tzinfo=utc), max_length=256),
            preserve_default=False,
        ),
    ]
