# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-31 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_trip_trip_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapoint',
            name='name',
        ),
        migrations.AddField(
            model_name='datapoint',
            name='alpha1',
            field=models.FloatField(default=10.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datapoint',
            name='alpha2',
            field=models.FloatField(default=2.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datapoint',
            name='alpha3',
            field=models.FloatField(default=3.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datapoint',
            name='alpha4',
            field=models.FloatField(default=5.0),
            preserve_default=False,
        ),
    ]
